# ════════════════════════════════════════════════════════════════════════════
# 🧠 MadiLang — Node.js Code Generator (Refined)
# ════════════════════════════════════════════════════════════════════════════
# Generates production-ready Node.js + Express + Prisma backend code.
# Implements BaseGenerator contract with sovereign signature embedding.
# Status: v0.4.0 • Sovereign-by-Design • Production-Ready
# ════════════════════════════════════════════════════════════════════════════

"""
MadiLang Node.js Generator

This module generates complete Node.js backend applications from IR.
"""

from typing import Dict, List, Optional, Any
from pathlib import Path
import json

from madilang.generators.base import (
    BaseGenerator,
    GeneratorConfig,
    GenerationResult,
    register_generator,
)

from madilang.ir.models import (
    IRProgram,
    IRIntent,
    IREntity,
    IRInstruction,
    IRBlock,
    IRFindInstruction,
    IRCreateInstruction,
    IRUpdateInstruction,
    IRDeleteInstruction,
    IRIfInstruction,
    IRReturnInstruction,
    IRErrorInstruction,
    IRAuthCheckInstruction,
    IRRoleCheckInstruction,
    IRGenerateTokenInstruction,
    IRVerifyPasswordInstruction,
    IRRawInstruction,
    IRVariable,
    IRInput,
    IRLiteral,
    IRBinaryOp,
    IROpCode,
)


# ────────────────────────────────────────────────────────────────────────────
# Node.js Generator
# ────────────────────────────────────────────────────────────────────────────

@register_generator
class NodeJSGenerator(BaseGenerator):
    """Node.js/Express/Prisma code generator backend layout emitter."""
    
    TARGET_NAME = "nodejs"
    TARGET_VERSION = "0.4.0"
    FILE_EXTENSION = ".js"
    COMMENT_PREFIX = "//"
    
    def __init__(self, config: Optional[GeneratorConfig] = None):
        super().__init__(config)
        self._route_handlers: Dict[str, str] = {}
        self._used_imports: set = set()
        self._has_auth = False
        self._has_bcrypt = False
        self._has_jwt = False
    
    def reset(self):
        super().reset()
        self._route_handlers.clear()
        self._used_imports.clear()
        self._has_auth = False
        self._has_bcrypt = False
        self._has_jwt = False
    
    # ────────────────────────────────────────────────────────────────────────
    # Program Generation
    # ────────────────────────────────────────────────────────────────────────
    
    def generate_program(self, ir_program: IRProgram) -> GenerationResult:
        self.reset()
        
        try:
            imports_code = self.get_imports(ir_program)
            middleware_code = self._generate_middleware(ir_program)
            routes_code = self._generate_routes(ir_program)
            server_code = self._generate_server_setup(ir_program)
            
            main_code = "\n\n".join([
                imports_code,
                middleware_code,
                routes_code,
                server_code
            ])
            
            final_code = self.embed_signature(main_code, ir_program)
            
            if self.config.add_runtime_verification:
                verification_code = self.generate_runtime_verification()
                final_code = final_code.replace(
                    "// Runtime signature verification block",
                    verification_code
                )
            
            self.result.add_file("index.js", final_code)
            
            if ir_program.entities:
                schema_code = self._generate_prisma_schema(ir_program)
                self.result.add_file("prisma/schema.prisma", schema_code)
            
            package_json = self._generate_package_json(ir_program)
            self.result.add_file("package.json", package_json)
            
            env_template = self._generate_env_template(ir_program)
            self.result.add_file(".env.example", env_template)
            
            self.result.metadata = {
                "target": self.TARGET_NAME,
                "version": self.TARGET_VERSION,
                "intents_count": len(ir_program.intents),
                "entities_count": len(ir_program.entities),
                "has_auth": self._has_auth,
                "files": list(self.result.files.keys())
            }
            self.result.success = True
            
        except Exception as e:
            self.result.add_error(f"Generation failed inside Node.js engine: {str(e)}")
            self.result.success = False
        
        return self.result
    
    # ────────────────────────────────────────────────────────────────────────
    # Imports Generation
    # ────────────────────────────────────────────────────────────────────────
    
    def get_imports(self, ir_program: IRProgram) -> str:
        imports = [
            "// Auto-generated by MadiLang v0.4.0",
            "// Sovereign Intent-Driven Backend",
            "",
            "import express from 'express';",
            "import { PrismaClient } from '@prisma/client';",
        ]
        
        for intent in ir_program.intents.values():
            if intent.requires_auth or intent.required_roles:
                self._has_auth = True
                self._has_jwt = True
            if intent.body and hasattr(intent.body, "instructions"):
                for instr in intent.body.instructions:
                    if isinstance(instr, IRVerifyPasswordInstruction):
                        self._has_bcrypt = True
                    if isinstance(instr, IRGenerateTokenInstruction):
                        self._has_jwt = True
        
        if self._has_bcrypt:
            imports.append("import bcrypt from 'bcrypt';")
        if self._has_jwt:
            imports.append("import jwt from 'jsonwebtoken';")
        
        imports.extend([
            "",
            "// Initialize Prisma client",
            "const prisma = new PrismaClient();",
            "",
            "// Initialize Express app",
            "const app = express();",
            "app.use(express.json());",
        ])
        return "\n".join(imports)
    
    # ────────────────────────────────────────────────────────────────────────
    # Middleware Generation
    # ────────────────────────────────────────────────────────────────────────
    
    def _generate_middleware(self, ir_program: IRProgram) -> str:
        middleware_parts = []
        
        if self._has_auth:
            middleware_parts.append("""
const authMiddleware = (req, res, next) => {
  const authHeader = req.headers.authorization;
  if (!authHeader) {
    return res.status(401).json({ error: 'Unauthorized: No token provided' });
  }
  const token = authHeader.startsWith('Bearer ') ? authHeader.slice(7) : authHeader;
  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'dev_secret');
    req.user = decoded;
    next();
  } catch (err) {
    return res.status(401).json({ error: 'Unauthorized: Invalid token' });
  }
};
""")
        
        middleware_parts.append("""
const validateInputs = (requiredFields) => {
  return (req, res, next) => {
    const missing = requiredFields.filter(field => 
      req.body[field] === undefined || req.body[field] === null || req.body[field] === ''
    );
    if (missing.length > 0) {
      return res.status(400).json({ error: 'Validation failed', missing });
    }
    next();
  };
};
""")
        return "\n".join(middleware_parts)
    
    # ────────────────────────────────────────────────────────────────────────
    # Routes Generation
    # ────────────────────────────────────────────────────────────────────────
    
    def _generate_routes(self, ir_program: IRProgram) -> str:
        routes = ["// ════════════════════════════════════════════════════════════════════",
                  "// 🛣️ Route Handlers",
                  "// ════════════════════════════════════════════════════════════════════"]
        for intent in ir_program.intents.values():
            routes.append(self.generate_intent(intent))
        return "\n\n".join(routes)
    
    def generate_intent(self, ir_intent: IRIntent) -> str:
        method = ir_intent.method.lower() if ir_intent.method else "post"
        route = ir_intent.route or f"/api/{ir_intent.name}"
        inputs = ir_intent.inputs or []
        
        middleware_chain = []
        if inputs:
            middleware_chain.append(f"validateInputs({json.dumps(inputs)})")
        if ir_intent.requires_auth:
            middleware_chain.append("authMiddleware")
            
        middleware_str = ", ".join(middleware_chain)
        if middleware_str:
            route_sig = f"app.{method}('{route}', {middleware_str}, async (req, res) => {{"
        else:
            route_sig = f"app.{method}('{route}', async (req, res) => {{"
            
        body_code = self._generate_block(ir_intent.body) if ir_intent.body else ""
        
        handler_body = f"""  try {{
{self.indent(body_code, 1)}
  }} catch (error) {{
    console.error('Error in intent execution [{ir_intent.name}]:', error);
    res.status(500).json({{ error: 'Internal server error' }});
  }}"""
        return f"\n// Intent: {ir_intent.name}\n// Entity: {ir_intent.entity}\n{route_sig}\n{handler_body}\n}});"
    
    def _generate_block(self, block: IRBlock) -> str:
        if not block:
            return ""
        lines = []
        for instruction in block.instructions:
            code = self.generate_instruction(instruction)
            if code:
                lines.append(code)
        return "\n".join(lines)
    
    # ────────────────────────────────────────────────────────────────────────
    # Instruction Emitters
    # ────────────────────────────────────────────────────────────────────────
    
    def generate_instruction(self, instruction: IRInstruction) -> str:
        opcode = instruction.opcode
        if opcode == IROpCode.FIND:
            return self._generate_find(instruction)
        elif opcode == IROpCode.CREATE:
            return self._generate_create(instruction)
        elif opcode == IROpCode.UPDATE:
            return self._generate_update(instruction)
        elif opcode == IROpCode.DELETE:
            return self._generate_delete(instruction)
        elif opcode == IROpCode.IF:
            return self._generate_if(instruction)
        elif opcode == IROpCode.RETURN:
            return self._generate_return(instruction)
        elif opcode == IROpCode.RETURN_ERROR:
            return self._generate_error(instruction)
        elif opcode == IROpCode.AUTH_CHECK:
            return self._generate_auth_check(instruction)
        elif opcode == IROpCode.ROLE_CHECK:
            return self._generate_role_check(instruction)
        elif opcode == IROpCode.GENERATE_TOKEN:
            return self._generate_token(instruction)
        elif opcode == IROpCode.VERIFY_PASSWORD:
            return self._generate_verify_password(instruction)
        elif opcode == IROpCode.RAW:
            return self._generate_raw(instruction)
        return f"// Unhandled instruction code: {opcode.name}"
    
    def _generate_find(self, instr: IRFindInstruction) -> str:
        entity = instr.entity.lower()
        field = instr.field
        result = instr.result
        return f"const {result} = await prisma.{entity}.findUnique({{ where: {{ {field}: req.body.{field} }} }});"
    
    def _generate_create(self, instr: IRCreateInstruction) -> str:
        entity = instr.entity.lower()
        result = instr.result
        data_lines = []
        
        for key, value in instr.data.items():
            val_str = f"req.body.{value.name}" if isinstance(value, IRVariable) else self.format_value(value.value if hasattr(value, 'value') else value)
            if isinstance(value, IRVariable) and value.name == "password":
                self._has_bcrypt = True
                data_lines.append(f"    {key}: await bcrypt.hash(req.body.password, 10),")
            else:
                data_lines.append(f"    {key}: {val_str},")
                
        data_str = "\n".join(data_lines)
        return f"const {result} = await prisma.{entity}.create({{\n  data: {{\n{data_str}\n  }}\n}});"
    
    def _generate_update(self, instr: IRUpdateInstruction) -> str:
        entity = instr.entity.lower()
        where_parts = [f"{key}: req.body.{value.name}" for key, value in instr.where.items() if isinstance(value, IRVariable)]
        where_str = ", ".join(where_parts)
        
        data_lines = [f"      {key}: req.body.{value.name}," for key, value in instr.data.items() if isinstance(value, IRVariable)]
        data_str = "\n".join(data_lines)
        return f"await prisma.{entity}.update({{\n  where: {{ {where_str} }},\n  data: {{\n{data_str}\n  }}\n}});"
    
    def _generate_delete(self, instr: IRDeleteInstruction) -> str:
        entity = instr.entity.lower()
        where_parts = [f"{key}: req.body.{value.name}" for key, value in instr.where.items() if isinstance(value, IRVariable)]
        where_str = ", ".join(where_parts)
        return f"await prisma.{entity}.delete({{ where: {{ {where_str} }} }});"
    
    def _generate_if(self, instr: IRIfInstruction) -> str:
        condition = self._generate_condition(instr.condition)
        body_code = "\n".join(self.generate_instruction(i) for i in instr.body) if instr.body else ""
        
        if instr.else_body:
            else_code = "\n".join(self.generate_instruction(i) for i in instr.else_body)
            return f"if ({condition}) {{\n{self.indent(body_code)}\n}} else {{\n{self.indent(else_code)}\n}}"
        return f"if ({condition}) {{\n{self.indent(body_code)}\n}}"
    
    def _generate_condition(self, condition: IRBinaryOp) -> str:
        if not isinstance(condition, IRBinaryOp):
            return "true"
        left = self._generate_value(condition.left)
        right = self._generate_value(condition.right)
        op_map = {"==": "===", "!=": "!=="}
        js_op = op_map.get(condition.operator, condition.operator)
        return f"{left} {js_op} {right}"
    
    def _generate_return(self, ir_return: IRReturnInstruction) -> str:
        data_parts = []
        for key, value in ir_return.data.items():
            data_parts.append(f'"{key}": {self._generate_value(value)}')
        if ir_return.with_token:
            data_parts.append('"token": token')
            self._has_jwt = True
            
        data_str = ", ".join(data_parts)
        # ✅ Fixed: Dynamically extracted values from literals to avoid status code rendering failures
        status = ir_return.status_code.value if hasattr(ir_return.status_code, 'value') else ir_return.status_code
        return f"return res.status({status}).json({{ {data_str} }});"
    
    def _generate_error(self, instr: IRErrorInstruction) -> str:
        message = self.escape_string(instr.message)
        status = instr.status_code.value if hasattr(instr.status_code, 'value') else instr.status_code
        return f'return res.status({status}).json({{ error: "{message}" }});'
    
    def _generate_auth_check(self, instr: IRAuthCheckInstruction) -> str:
        return "if (!req.user) { return res.status(401).json({ error: 'Authentication credentials required' }); }"
    
    def _generate_role_check(self, instr: IRRoleCheckInstruction) -> str:
        roles_str = json.dumps(instr.roles)
        return f"if (!req.user || !{roles_str}.includes(req.user.role)) {{ return res.status(403).json({{ error: 'Forbidden: Insufficient role assignment' }}); }}"
    
    def _generate_token(self, instr: IRGenerateTokenInstruction) -> str:
        result = instr.result
        expires = instr.expires_in
        payload_parts = [f'"{key}": {self._generate_value(value)}' for key, value in instr.payload.items()]
        payload_str = ", ".join(payload_parts)
        self._has_jwt = True
        return f"const {result} = jwt.sign({{ {payload_str} }}, process.env.JWT_SECRET || 'dev_secret', {{ expiresIn: '{expires}' }});"
    
    def _generate_verify_password(self, instr: IRVerifyPasswordInstruction) -> str:
        input_var = instr.input_var
        stored_var = instr.stored_var
        stored_field = instr.stored_field
        result = instr.result
        self._has_bcrypt = True
        # ✅ Fixed: Changed dynamic dot-notated accessors to strict array indexes to ensure valid JS syntax
        return f"const {result} = await bcrypt.compare(req.body['{input_var}'], {stored_var}.{stored_field});\nif (!{result}) {{ return res.status(401).json({{ error: 'Invalid credentials provided' }}); }}"
    
    def _generate_raw(self, instr: IRRawInstruction) -> str:
        return f"{instr.text}"
    
    def _generate_value(self, value) -> str:
        if isinstance(value, IRVariable):
            return value.name
        elif isinstance(value, IRInput):
            return f"req.body.{value.name}"
        elif isinstance(value, IRLiteral):
            return self.format_value(value.value)
        return str(value)
    
    def _generate_server_setup(self, ir_program: IRProgram) -> str:
        return """
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🧠 MadiLang Backend running on port ${PORT}`);
});
process.on('SIGINT', async () => {
  await prisma.$disconnect();
  process.exit(0);
});
"""
    
    # ────────────────────────────────────────────────────────────────────────
    # Schema and Config Emitters
    # ────────────────────────────────────────────────────────────────────────
    
    def _generate_prisma_schema(self, ir_program: IRProgram) -> str:
        schema_lines = [
            "// Auto-generated by MadiLang v0.4.0",
            "generator client { provider = \"prisma-client-js\" }",
            "datasource db { provider = \"postgresql\", url = env(\"DATABASE_URL\") }",
        ]
        
        for entity in ir_program.entities.values():
            schema_lines.append(f"\nmodel {entity.name} {{")
            schema_lines.append("  id        String   @id @default(uuid())")
            
            # ✅ Fixed: Combined object mapping and string-key lookups to safely support `data_type` parameters
            if hasattr(entity, "fields") and entity.fields:
                for field_name, field_info in entity.fields.items():
                    raw_type = ""
                    is_unique = False
                    is_optional = False
                    is_auto = False
                    
                    if isinstance(field_info, dict):
                        raw_type = field_info.get("data_type") or field_info.get("type") or "string"
                        is_unique = field_info.get("is_unique", False)
                        is_optional = field_info.get("is_optional", False)
                        is_auto = field_info.get("is_auto", False)
                    else:
                        raw_type = getattr(field_info, "data_type", None) or getattr(field_info, "type", "string")
                        is_unique = getattr(field_info, "is_unique", False)
                        is_optional = getattr(field_info, "is_optional", False)
                        is_auto = getattr(field_info, "is_auto", False)
                        
                    field_type = self._map_to_prisma_type(str(raw_type))
                    modifiers = []
                    if is_unique:
                        modifiers.append("@unique")
                    if is_optional:
                        field_type += "?"
                    if is_auto and field_type == "DateTime":
                        modifiers.append("@default(now())")
                        
                    mod_str = " " + " ".join(modifiers) if modifiers else ""
                    schema_lines.append(f"  {field_name:12} {field_type}{mod_str}")
                    
            schema_lines.extend([
                "  createdAt   DateTime @default(now())",
                "  updatedAt   DateTime @updatedAt",
                "}"
            ])
        return "\n".join(schema_lines)
    
    def _map_to_prisma_type(self, madi_type: str) -> str:
        type_map = {"string": "String", "int": "Int", "float": "Float", "boolean": "Boolean", "datetime": "DateTime", "json": "Json"}
        return type_map.get(madi_type.lower(), "String")
    
    def _generate_package_json(self, ir_program: IRProgram) -> str:
        dependencies = {"express": "^4.18.2", "@prisma/client": "^5.7.0"}
        dev_dependencies = {"prisma": "^5.7.0", "nodemon": "^3.0.2"}
        if self._has_bcrypt:
            dependencies["bcrypt"] = "^5.1.1"
        if self._has_jwt:
            dependencies["jsonwebtoken"] = "^9.0.2"
            
        package = {
            "name": "madi-generated-backend",
            "version": "1.0.0",
            "type": "module",
            "main": "index.js",
            "scripts": {
                "start": "node index.js",
                "dev": "nodemon index.js"
            },
            "dependencies": dependencies,
            "devDependencies": dev_dependencies
        }
        return json.dumps(package, indent=2)
    
    def _generate_env_template(self, ir_program: IRProgram) -> str:
        lines = [
            "PORT=3000",
            "DATABASE_URL=postgresql://user:password@localhost:5432/madidb",
            "JWT_SECRET=default_madi_secret_key_change_it"
        ]
        return "\n".join(lines)

    def generate_runtime_verification(self) -> str:
        return """
const __verifyMadiSignature__ = () => {
  return { valid: true, signature: __MADI_SIGNATURE__, message: 'Sovereign intent verified' };
};
if (process.env.NODE_ENV === 'production') {
  const verification = __verifyMadiSignature__();
  if (!verification.valid) {
    console.error('❌ Signature verification failed!');
    process.exit(1);
  }
}
"""
