# Auto-generated by MadiLang Compiler
# API Generator v0.4 (AST + JWT + Middleware Engine)

from core.step_compiler import StepCompiler


class APIGenerator:
    def __init__(self, data):
        self.data = data

    def generate(self):
        entity = self.data["entity"]
        path = self.data["path"]
        method = self.data["method"].lower()
        inputs = self.data["inputs"]

        compiler = StepCompiler()
        steps = compiler.compile(self.data["steps"])

        code = ""

        # ========================
        # DETECT FEATURES
        # ========================
        use_auth = False

        for step in steps:
            if step["type"] == "protect_route":
                use_auth = True

        # ========================
        # IMPORTS
        # ========================
        code += "// Auto-generated by MadiLang\n"
        code += "import express from 'express';\n"
        code += "import prisma from './prisma';\n"
        code += "import bcrypt from 'bcrypt';\n"
        code += "import jwt from 'jsonwebtoken';\n\n"

        # ========================
        # APP SETUP
        # ========================
        code += "const app = express();\n"
        code += "app.use(express.json());\n\n"

        # ========================
        # MIDDLEWARE (IF NEEDED)
        # ========================
        if use_auth:
            code += """
const authMiddleware = (req, res, next) => {
  const token = req.headers.authorization;

  if (!token) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET || 'dev_secret');
    req.user = decoded;
    next();
  } catch (err) {
    return res.status(401).json({ error: "Invalid token" });
  }
};

"""

        # ========================
        # ROUTE DEFINITION
        # ========================
        if use_auth:
            code += f"app.{method}('{path}', authMiddleware, async (req, res) => {{\n"
        else:
            code += f"app.{method}('{path}', async (req, res) => {{\n"

        # ========================
        # INPUTS
        # ========================
        if inputs:
            code += f"  const {{ {', '.join(inputs)} }} = req.body;\n\n"

            code += "  if (!" + " || !".join(inputs) + ") {\n"
            code += "    return res.status(400).json({ error: 'Missing fields' });\n"
            code += "  }\n\n"

        # ========================
        # STEPS ENGINE (AST)
        # ========================
        for step in steps:
            t = step["type"]

            # 🔐 PROTECT ROUTE (already handled)
            if t == "protect_route":
                continue

            # 🔍 FIND
            elif t == "find":
                code += f"""
  const {step['as']} = await prisma.{step['entity'].lower()}.findUnique({{
    where: {{ {step['field']}: {step['field']} }}
  }});
"""

            # ❌ NOT FOUND
            elif t == "if_not_found":
                code += f"""
  if (!{step['var']}) {{
    return res.status(404).json({{ error: '{step['var']} not found' }});
  }}
"""

            # ❗ EXISTS
            elif t == "if_exists":
                code += f"""
  if ({step['var']}) {{
    return res.status(400).json({{ error: '{step['var']} already exists' }});
  }}
"""

            # 🔐 PASSWORD CHECK
            elif t == "password_mismatch":
                code += f"""
  const valid = await bcrypt.compare(password, {step['var']}.{step['field']});
  if (!valid) {{
    return res.status(401).json({{ error: 'Invalid credentials' }});
  }}
"""

            # 🧱 CREATE
            elif t == "create":
                code += f"""
  const result = await prisma.{entity.lower()}.create({{
    data: {{
"""
                for inp in inputs:
                    if inp == "password":
                        code += "      password: await bcrypt.hash(password, 10),\n"
                    else:
                        code += f"      {inp}: {inp},\n"

                code += """    }
  });
"""

            # 🎟 JWT SUCCESS
            elif t == "success":
                code += """
  const token = jwt.sign(
    { id: user?.id || result?.id },
    process.env.JWT_SECRET || 'dev_secret',
    { expiresIn: '7d' }
  );

  return res.json({ success: true, token });
"""

            # ❌ ERROR
            elif t == "error":
                code += f"""
  return res.status(400).json({{ error: "{step['message']}" }});
"""

        # ========================
        # END ROUTE
        # ========================
        code += "\n});\n\n"

        # ========================
        # SERVER START
        # ========================
        code += "app.listen(3000, () => console.log('MadiLang running'));\n"

        return code
