# Auto-generated by MadiLang Compiler
# API Generator v0.2 (AST + Legacy Support)

import jwt from 'jsonwebtoken';
from core.step_compiler import StepCompiler

import bcrypt

class APIGenerator:
    def __init__(self, data):
        self.data = data

    def generate(self):
        entity = self.data["entity"]
        path = self.data["path"]
        method = self.data["method"].lower()
        inputs = self.data["inputs"]
        compiler = StepCompiler()
steps = compiler.compile(self.data["steps"])

        code = ""

        code += "// Auto-generated by MadiLang\n"
        code += "import express from 'express';\n"
        code += "import prisma from './prisma';\n"
        code += "import bcrypt from 'bcrypt';\n\n"

        code += "const app = express();\n"
        code += "app.use(express.json());\n\n"

        code += f"app.{method}('{path}', async (req, res) => {{\n"

        # Inputs
        code += "  const { " + ", ".join(inputs) + " } = req.body;\n\n"

        # Validation
        code += "  if (!" + " || !".join(inputs) + ") {\n"
        code += "    return res.status(400).json({ error: 'Missing fields' });\n"
        code += "  }\n\n"

        # ----------------------------
        # STEPS ENGINE (AST + LEGACY)
        # ----------------------------

        for step in steps:
    t = step["type"]

    # 🔍 FIND USER
    if t == "find":
        entity = step["entity"]
        field = step["field"]
        var = step["as"]

        code += f"  const {var} = await prisma.{entity.lower()}.findUnique({{\n"
        code += f"    where: {{ {field} }}\n"
        code += "  });\n\n"

    # ❌ IF NOT FOUND
    elif t == "if_not_found":
        var = step["var"]
        code += f"  if (!{var}) {{\n"
        code += f"    return res.status(404).json({{ error: '{var} not found' }});\n"
        code += "  }\n\n"

    # ❗ IF EXISTS
    elif t == "if_exists":
        var = step["var"]
        code += f"  if ({var}) {{\n"
        code += f"    return res.status(400).json({{ error: '{var} already exists' }});\n"
        code += "  }\n\n"

    # 🔐 PASSWORD CHECK
    elif t == "password_mismatch":
        var = step["var"]
        field = step["field"]

        code += f"  const isMatch = await bcrypt.compare(password, {var}.{field});\n"
        code += "  if (!isMatch) {\n"
        code += "    return res.status(401).json({ error: 'Invalid password' });\n"
        code += "  }\n\n"

    # 🧱 CREATE USER
    elif t == "create":
        code += f"  const result = await prisma.{entity.lower()}.create({{\n"
        code += "    data: {\n"

        for inp in inputs:
            if inp == "password":
                code += "      password: await bcrypt.hash(password, 10),\n"
            else:
                code += f"      {inp}: {inp},\n"

        code += "    }\n"
        code += "  });\n\n"

    # ❌ ERROR MESSAGE
    elif t == "error":
        msg = step["message"]
        code += f"  return res.status(400).json({{ error: '{msg}' }});\n\n"

    # ✅ SUCCESS
    elif t == "success":
        code += "  return res.json({ success: true });\n\n"

            # ===== AST MODE =====
            if isinstance(step, dict):
                t = step.get("type")

                # FIND ENTITY
                if t == "find":
                    code += f"""
  const {step['var']} = await prisma.{step['entity']}.findUnique({{
    where: {{ {step['field']}: {step['field']} }}
  }});
"""

                # IF NOT FOUND
                elif t == "if_not_found":
                    code += f"""
  if (!{step['var']}) {{
    return res.status(404).json({{ error: 'Not found' }});
  }}
"""

                # PASSWORD CHECK
                elif t == "password_mismatch":
                    code += f"""
  const valid = await bcrypt.compare(password, {step['var']}.{step['field']});
  if (!valid) {{
    return res.status(401).json({{ error: 'Invalid credentials' }});
  }}
"""

                # CREATE USER
                elif t == "create_user":
                    code += f"""
  const result = await prisma.{entity.lower()}.create({{
    data: {{
"""
                    for inp in inputs:
                        if inp == "password":
                            code += "      password: await bcrypt.hash(password, 10),\n"
                        else:
                            code += f"      {inp}: {inp},\n"

                    code += """    }
  });
"""

                # ERROR
                elif t == "error":
                    code += f"""
  return res.status(400).json({{ error: "{step['message']}" }});
"""

                # SUCCESS
                elif t == "success":
                    code += """
  return res.json({ success: true });
"""

            # ===== LEGACY MODE (BACKWARD COMPATIBILITY) =====
            elif isinstance(step, str):

                if "validate email" in step:
                    code += """
  if (!email.includes('@')) {
    return res.status(400).json({ error: 'Invalid email' });
  }
"""

                elif "create user" in step:
                    code += f"""
  const result = await prisma.{entity.lower()}.create({{
    data: {{
"""
                    for inp in inputs:
                        if inp == "password":
                            code += "      password: await bcrypt.hash(password, 10),\n"
                        else:
                            code += f"      {inp}: {inp},\n"

                    code += """    }
  });
"""

        # Response
        code += """
  return res.json({ success: true, data: result });
"""

        code += "});\n\n"

        code += "app.listen(3000, () => console.log('MadiLang running'));\n"

        return code

        elif step["type"] == "login":
    code += """
  const user = await prisma.user.findUnique({
    where: { email }
  });

  if (!user) {
    return res.status(404).json({ error: 'User not found' });
  }
"""

elif step["type"] == "verify_password":
    code += """
  const valid = await bcrypt.compare(password, user.password);

  if (!valid) {
    return res.status(401).json({ error: 'Invalid credentials' });
  }
"""

elif step["type"] == "generate_token":
    code += """
  const token = jwt.sign(
    { id: user.id, email: user.email },
    process.env.JWT_SECRET,
    { expiresIn: '24h' }
  );
"""

elif step["type"] == "protect_route":
    code += """
  // Middleware: verify JWT required
  const token = req.headers.authorization;

  if (!token) {
    return res.status(401).json({ error: 'No token provided' });
  }
"""
