class APIGenerator:
    def __init__(self, data):
        self.data = data

    def generate(self):
        entity = self.data["entity"]
        path = self.data["path"]
        method = self.data["method"].lower()
        inputs = self.data["inputs"]
        steps = self.data["steps"]

        code = ""
        code += "// Auto-generated by MadiLang\n"
        code += "import express from 'express';\n"
        code += "import prisma from './prisma';\n"
        code += "import bcrypt from 'bcrypt';\n\n"

        code += "const app = express();\n"
        code += "app.use(express.json());\n\n"

        code += f"app.{method}('{path}', async (req, res) => {{\n"

        # inputs
        code += "  const { " + ", ".join(inputs) + " } = req.body;\n\n"

        # validation
        code += "  if (!" + " || !".join(inputs) + ") {\n"
        code += "    return res.status(400).json({ error: 'Missing fields' });\n"
        code += "  }\n\n"

        # steps logic
        for step in steps:
            if "validate email" in step:
                code += "  if (!email.includes('@')) {\n"
                code += "    return res.status(400).json({ error: 'Invalid email' });\n"
                code += "  }\n\n"

        # DB CREATE (BINDING 🔥)
        code += f"  const result = await prisma.{entity.lower()}.create({{\n"
        code += "    data: {\n"

        for inp in inputs:
            if inp == "password":
                code += "      password: await bcrypt.hash(password, 10),\n"
            else:
                code += f"      {inp}: {inp},\n"

        code += "    }\n"
        code += "  });\n\n"

        code += "  return res.json({ success: true, data: result });\n"
        code += "});\n\n"

        code += "app.listen(3000, () => console.log('MadiLang running'));\n"

        return code
