class DBGenerator:
    """
    يحول entity في MadiLang إلى Prisma Schema
    """

    def __init__(self, entity_name, fields):
        self.entity_name = entity_name
        self.fields = fields

    def generate(self):
        schema = "// Auto-generated by MadiLang DB Engine\n\n"
        schema += "generator client {\n"
        schema += "  provider = \"prisma-client-js\"\n"
        schema += "}\n\n"

        schema += "datasource db {\n"
        schema += "  provider = \"postgresql\"\n"
        schema += "  url = env(\"DATABASE_URL\")\n"
        schema += "}\n\n"

        schema += f"model {self.entity_name} {{\n"
        schema += "  id String @id @default(uuid())\n"

        for field in self.fields:
            parts = field.split()
            name = parts[0]
            type_ = "String"
            mods = parts[1:] if len(parts) > 1 else []

            schema += f"  {name} {type_}"

            if "unique" in mods:
                schema += " @unique"

            if "secret" in mods:
                schema += " /// @encrypted"

            schema += "\n"

        schema += "}\n"

        return schema
