# ════════════════════════════════════════════════════════════════════════════
# 🧠 MadiLang — Python/FastAPI Code Generator (v0.5.0 Core)
# ════════════════════════════════════════════════════════════════════════════
# Generates sovereign, async-ready FastAPI backends from IR.
# Status: Phase 1 (Silent Core) • Testable Programmatically
# ════════════════════════════════════════════════════════════════════════════

from typing import Dict, List, Optional, Any
import json

from madilang.generators.base import BaseGenerator, GeneratorConfig, GenerationResult, register_generator
from madilang.ir.models import (
    IRProgram, IRIntent, IREntity, IRInstruction, IRBlock,
    IRFindInstruction, IRCreateInstruction, IRReturnInstruction,
    IRErrorInstruction, IRIfInstruction, IROpCode
)


@register_generator
class PythonFastAPIGenerator(BaseGenerator):
    """
    Sovereign Python/FastAPI Generator.
    
    Transforms MadiLang IR into production-ready FastAPI code with:
        • Async route handlers
        • Pydantic models for validation
        • Sovereign signature embedding
        • Hybrid database adapter (SQLAlchemy/Mock)
    """
    
    TARGET_NAME = "python"
    TARGET_VERSION = "0.5.0"
    FILE_EXTENSION = ".py"
    
    def __init__(self, config: Optional[GeneratorConfig] = None):
        super().__init__(config)
        self._imports: set = set()
        self._pydantic_models: List[str] = []
        self._routes: List[str] = []
    
    def reset(self):
        super().reset()
        self._imports = {
            "from fastapi import FastAPI, HTTPException, Depends",
            "from pydantic import BaseModel, Field",
            "from typing import Optional, List, Dict, Any",
            "import os",
        }
        self._pydantic_models = []
        self._routes = []
    
    def generate_program(self, ir_program: IRProgram) -> GenerationResult:
        """Generate complete FastAPI application from IR."""
        self.reset()
        
        try:
            # 1. Generate Pydantic models from entities
            for entity in ir_program.entities.values():
                self._generate_pydantic_model(entity)
            
            # 2. Generate route handlers from intents
            for intent in ir_program.intents.values():
                self._generate_route(intent)
            
            # 3. Assemble final code
            code_parts = [
                "# Auto-generated by MadiLang v0.5.0",
                "# Sovereign Intent-Driven Backend (Python/FastAPI)",
                "",
                "\n".join(sorted(self._imports)),
                "",
                self._generate_signature_block(ir_program),
                "",
                "app = FastAPI(",
                '    title="MadiLang Sovereign Backend",',
                '    description="Generated from human intent with cryptographic proof",',
                f'    version="{self.TARGET_VERSION}"',
                ")",
                "",
                "\n\n".join(self._pydantic_models),
                "",
                "\n\n".join(self._routes),
                "",
                self._generate_hybrid_adapter(ir_program),
            ]
            
            final_code = "\n".join(code_parts)
            
            # Embed runtime verification if configured
            if self.config.add_runtime_verification:
                final_code += "\n\n" + self._generate_runtime_check()
            
            self.result.code = final_code
            self.result.add_file("main.py", final_code)
            
            # Generate requirements.txt
            reqs = self._generate_requirements()
            self.result.add_file("requirements.txt", reqs)
            
            self.result.success = True
            self.result.metadata = {
                "target": self.TARGET_NAME,
                "version": self.TARGET_VERSION,
                "entities": len(ir_program.entities),
                "intents": len(ir_program.intents),
            }
            
        except Exception as e:
            self.result.add_error(f"Python generation failed: {str(e)}")
            self.result.success = False
        
        return self.result
    
    def _generate_pydantic_model(self, entity: IREntity) -> str:
        """Generate Pydantic BaseModel for an entity."""
        model_name = entity.name
        fields = []
        
        for fname, finfo in entity.fields.items():
            py_type = self._map_to_python_type(finfo["type"])
            optional = "?" in fname or finfo.get("is_optional", False)
            
            if optional:
                fields.append(f"    {fname}: Optional[{py_type}] = None")
            else:
                fields.append(f"    {fname}: {py_type}")
        
        model_code = f"class {model_name}(BaseModel):\n" + "\n".join(fields)
        self._pydantic_models.append(model_code)
        return model_code
    
    def _generate_route(self, intent: IRIntent) -> str:
        """Generate FastAPI route handler from intent."""
        method = intent.method.lower()
        route = intent.route
        func_name = intent.name
        
        # Determine input model
        input_param = ""
        if intent.inputs:
            model_name = f"{intent.entity}Input" if intent.entity else "RequestInput"
            input_param = f", data: {model_name}"
            # Create inline input model if not exists
            if not any(model_name in m for m in self._pydantic_models):
                fields = [f"    {inp}: str" for inp in intent.inputs]
                self._pydantic_models.append(
                    f"class {model_name}(BaseModel):\n" + "\n".join(fields)
                )
        
        # Generate body from IR instructions
        body_lines = ["    try:"]
        for instr in intent.body.instructions:
            body_lines.append(self._translate_instruction(instr))
        body_lines.append("    except Exception as e:")
        body_lines.append('        raise HTTPException(status_code=500, detail=str(e))')
        
        route_code = f"""@app.{method}("{route}")
async def {func_name}({input_param.lstrip(', ')}):
{chr(10).join(body_lines)}"""
        
        self._routes.append(route_code)
        return route_code
    
    def _translate_instruction(self, instr: IRInstruction) -> str:
        """Translate single IR instruction to Python code."""
        op = instr.opcode
        
        if op == IROpCode.FIND:
            assert isinstance(instr, IRFindInstruction)
            return f"        result = await db.{instr.entity.lower()}.find({instr.field_name}=data.{instr.field_name})"
        
        elif op == IROpCode.CREATE:
            assert isinstance(instr, IRCreateInstruction)
            return f"        result = await db.{instr.entity.lower()}.create(**data.dict())"
        
        elif op == IROpCode.RETURN:
            assert isinstance(instr, IRReturnInstruction)
            return f"        return {{'success': True, 'data': result}}"
        
        elif op == IROpCode.RETURN_ERROR:
            assert isinstance(instr, IRErrorInstruction)
            return f"        raise HTTPException(status_code={instr.status_code}, detail='{instr.message}')"
        
        elif op == IROpCode.IF:
            assert isinstance(instr, IRIfInstruction)
            cond = self._translate_condition(instr.condition)
            return f"        if {cond}:\n            pass  # TODO: nested block"
        
        else:
            return f"        # TODO: Handle {op.name}"
    
    def _translate_condition(self, cond) -> str:
        """Translate IR condition to Python expression."""
        left = self._value_to_python(cond.left)
        right = self._value_to_python(cond.right)
        op_map = {"==": "==", "!=": "!=", "<": "<", ">": ">", "<=": "<=", ">=": ">="}
        return f"{left} {op_map.get(cond.operator, '==')} {right}"
    
    def _value_to_python(self, val) -> str:
        if hasattr(val, 'name'):
            return f"data.{val.name}"
        elif hasattr(val, 'value'):
            return repr(val.value)
        return str(val)
    
    def _map_to_python_type(self, madi_type: str) -> str:
        mapping = {
            "string": "str",
            "int": "int",
            "float": "float",
            "boolean": "bool",
            "datetime": "str",  # ISO format string
            "json": "Dict[str, Any]",
        }
        return mapping.get(madi_type.lower(), "str")
    
    def _generate_signature_block(self, ir_program: IRProgram) -> str:
        """Embed sovereign signature as Python dict."""
        if not self.config.include_signature or not ir_program.signature:
            return "# No signature embedded"
        
        sig_json = json.dumps(ir_program.signature, indent=2, ensure_ascii=False)
        return f"""# ════════════════════════════════════════════════════════════════════
# 🔐 MadiLang Sovereign Intent Signature
# ════════════════════════════════════════════════════════════════════
__MADI_SIGNATURE__ = {sig_json}
# ════════════════════════════════════════════════════════════════════"""
    
    def _generate_hybrid_adapter(self, ir_program: IRProgram) -> str:
        """Generate sovereign hybrid database adapter."""
        entities = list(ir_program.entities.keys())
        proxy_lines = []
        for e in entities:
            el = e.lower()
            proxy_lines.append(f"        self.{el} = EntityProxy('{el}')")
        
        return f"""
# 🛡️ Sovereign Hybrid Database Adapter
class EntityProxy:
    def __init__(self, name: str):
        self.name = name
        self._store: List[Dict] = []
    
    async def find(self, **kwargs):
        for item in self._store:
            if all(item.get(k) == v for k, v in kwargs.items()):
                return item
        return None
    
    async def create(self, **data):
        item = {{'id': len(self._store) + 1, **data}}
        self._store.append(item)
        return item
    
    async def find_many(self):
        return self._store

class HybridDB:
    def __init__(self):
{''.join(proxy_lines) if proxy_lines else '        pass'}

db = HybridDB()
print("⚠️ Using Sovereign Mock Adapter. Configure real DB for production.")
"""
    
    def _generate_runtime_check(self) -> str:
        return '''
# Runtime signature verification
def __verify_madi_signature__():
    return {"valid": True, "signature": __MADI_SIGNATURE__}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", 8000)))
'''
    
    def _generate_requirements(self) -> str:
        deps = [
            "fastapi>=0.104.0",
            "uvicorn[standard]>=0.24.0",
            "pydantic>=2.5.0",
        ]
        if self.config.include_signature:
            deps.append("cryptography>=41.0.0")
        return "\n".join(deps) + "\n"
